config/routes.rb
Rails.application.routes.draw do
   root to: 'kittens#index'
   resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash.notice = "Kitten was successfully created"
      redirect_to root_path
    else
      flash.now.alert = "Oops, something went wrong!"
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def edit
  end

  def update
    if @kitten.update(kitten_params)
      flash.notice = "Kitten was successfully updated"
      redirect_to root_path
    else
      flash.now.alert = "Oops, something went wrong!"
      render :edit
    end
  end

  def destroy
    @kitten.destroy
    flash.notice = "Kitten was deleted"
    redirect_to root_path
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div class = "form">
  <%= form_for @kitten do |f| %>
  <ul>
    <% @kitten.errors.full_messages.each do |e| %>
      <li><%= e %> </li>
    <% end %>
  </ul>
    <p>
      <%= f.label :name  %>
      <%= f.text_field :name, class: "form_field"%>
    </p>
    <p>
      <%= f.label :age %>
      <%= f.number_field :age, in: [1, 10], class: "form_field" %>
    </p>
    <p>
      <%= f.label :cuteness %>
      <%= f.number_field :cuteness, in: [1, 10], class: "form_field" %>
    </p>
    <p>
      <%= f.label :softness %>
      <%= f.number_field :softness, in: [1, 10], class: "form_field" %>
    </p>
    <p>
      <%= f.submit "Submit", class: "button" %>
    </p>
  <% end %>
</div>

app/views/kittens/edit.html.erb
<h2>Edit Kitten</h2>

<%= render 'form' %>

app/views/kittens/index.html.erb
<h2>All Kittens</h2>

<table id="kittens">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
      <th></th>
    </tr>
  </thead>
  <body>
    <% @kittens.each do |k| %>
      <tr>
        <td><%= link_to k.name, k %></td>
        <td><%= k.age %></td>
        <td><%= k.cuteness %></td>
        <td><%= k.softness %></td>
        <td><%= link_to 'Delete', kitten_path(k), method: :delete %>
      </tr>
    <% end %>
  </body>
</table>

<p>
  <%= link_to 'Add Kitten', new_kitten_path %>
</p>

app/views/kittens/new.html.erb
<h2>Add a New Kitten</h2>

<%= render 'form' %>

app/views/kittens/show.html.erb
<h2><%= @kitten.name %></h2>

<table id="kittens">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
    </tr>
  </thead>
  <body>
    <tr>
      <td><%= @kitten.name %></td>
      <td><%= @kitten.age %></td>
      <td><%= @kitten.cuteness %></td>
      <td><%= @kitten.softness %></td>
    </tr>
  </body>
</table>


<p>
  <%= link_to 'Edit', edit_kitten_path %>
  <%= link_to 'Delete', kitten_path(@kitten), method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'HOME', root_path %></li>
    </ul>

    <p>
      <% flash.each do |type, msg| %>
        <%= msg %>
      <% end %>
    </p>

    <%= yield %>
  </body>
</html>